format = """
 ▲ 👟 \
 $all\
 $fill\
 $cmd_duration\
 $line_break\
 $character
"""

[character]
format = ' '

[directory]
truncation_length = 1

[git_branch]
symbol = ''
style = 'red'

[git_status]
disabled = true

[fill]
symbol = ' '

[python]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[cmd_duration]
format = '[took $duration]($style) '
style = 'bold yellow'
min_time = 2_000  # only show duration for commands longer than 2 seconds

[line_break]
disabled = false

palette = "onedark"

[palettes.onedark]
dark_blue = '#61afef'
blue = '#56b6c2'
red = '#e06c75'
green = '#98c379'
purple = '#c678dd'
cyan = '#56b6c2'
orange = '#be5046'
yellow = '#e5c07b'
gray = '#828997'
white = '#abb2bf'
black = '#2c323c'
