# Main format string
format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

palette = "onedark"

# Shows current directory
[directory]
truncation_length = 1
read_only_style = '197'
read_only = '  '
format = '[$path]($style)[$read_only]($read_only_style) '

# Git branch and status
[git_branch]
symbol = ' '

[git_status]
staged = '[ $count](green)'
deleted = '[ $count](red)'
untracked = '[ $count](yellow)'
modified = '[ $count](blue)'  
renamed = '[ $count](purple)'  
format = '$all_status$ahead_behind'  # Display all statuses

# Fill element (space)
[fill]
symbol = ' '

# Language icons
[python]
symbol = ' '
pyenv_version_name = true

[lua]
symbol = ' '

[nodejs]
symbol = ' '

[golang]
symbol = ' '

[haskell]
symbol = ' '

[rust]
symbol = ' '

[ruby]
symbol = ' '

# Package version
[package]
symbol = '󰏗 '

# AWS section
[aws]
symbol = ' '

# Docker context section
[docker_context]
symbol = ' '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

# Jobs (background processes)
[jobs]
symbol = ' '
number_threshold = 2  # Only show when multiple jobs are running

# Command duration
[cmd_duration]
format = '[took $duration]($style) '
style = 'bold yellow'
min_time = 2_000  # Only show duration for commands longer than 2 seconds

# Line break and prompt character
[line_break]
disabled = false

[character]
success_symbol = '❯ '  # Custom prompt character on success
error_symbol = '❯ '    # Custom prompt character on error

# OneDark color palette
[palettes.onedark]
dark_blue = '#61afef'
blue = '#56b6c2'
red = '#e06c75'
green = '#98c379'
purple = '#c678dd'
cyan = '#56b6c2'
orange = '#be5046'
yellow = '#e5c07b'
gray = '#828997'
white = '#abb2bf'
black = '#2c323c'
